services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: api_esq
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'development' ];
      then npx nodemon --legacy-watch server.js;
      else node server.js;
      fi"

  db:
    image: mariadb:10.11
    container_name: db_esq
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_esq
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PMA_HOST: db
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: redis_esq
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1000", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  db_data:
  redis_data:
