version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: api_esq_prod
    ports:
      - "${PORT}:3000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.11
    container_name: db_esq_prod
    restart: always
    env_file:
      - .env.prod
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_esq_prod
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env.prod
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: redis_esq
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1000", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  db_data:
  redis_data: